name: Test Heredoc
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test heredoc
        run: |
          cat <<EOF > test.txt
          Hello Ivan
          EOF
          cat test.txt
